name: 3DLand
favicon: null
layout_spectrum: 0.49882
typography_spectrum: 0.6584180239588022
title: 3D Robots
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-153984
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d7ad5'
    - '#d3dae2'
    - '#091018'
    - '#2a4c6f'
    - '#ab8372'
  brandStrength: 0.5
  lightness: 0.2538946697022766
  saturation: 0.9376813962589949
  rhythmicContrast: 0.5586431124247611
purpose: []
