name: 3DLand
favicon: null
layout_spectrum: 0.9131512329913676
typography_spectrum: 0.6584180239588022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.16738796094432473
  lightness: 0.2538946697022766
  saturation: 0.9376813962589949
  rhythmicContrast: 0.5586431124247611
purpose: []
